# Measures the claims in docs/why-the-translation-works-for-you-and-not-for-your-teammate.md
# from inside a running Godot process. The surrounding shell script puts the
# throwaway project into one disk state per case, sets LGCASE, and launches this.
#
# Nothing here is asserted from memory: every claim reads either the running
# TranslationServer or the project directory as it exists at this moment.
extends SceneTree

var failures := 0
var measured := 0

func check(id: String, desc: String, ok: bool, detail: String = "") -> void:
	measured += 1
	if not ok:
		failures += 1
	print(("PASS  " if ok else "FAIL  ") + id + "  " + desc)
	if detail != "":
		print("        " + detail)

func project_files() -> Array:
	var out := []
	var d := DirAccess.open("res://")
	if d != null:
		for f in d.get_files():
			out.append(f)
	out.sort()
	return out

func imported_md5_count() -> int:
	var d := DirAccess.open("res://.godot/imported")
	if d == null:
		return 0
	var n := 0
	for f in d.get_files():
		if f.ends_with(".md5"):
			n += 1
	return n

func _init() -> void:
	var c := OS.get_environment("LGCASE")
	print("CASE " + c)
	var files := project_files()
	var registered: PackedStringArray = ProjectSettings.get_setting(
		"internationalization/locale/translations", PackedStringArray())
	var greeting := tr("GREETING")

	match c:
		"never_imported":
			check("M4", "a project that was never imported returns the key itself",
				greeting == "GREETING", "tr(\"GREETING\") = " + greeting)
			check("M4b", "and ResourceLoader cannot see the CSV that is sitting right there",
				not ResourceLoader.exists("res://strings.csv") \
				and files.has("strings.csv"),
				"files = " + str(files))

		"fresh_import":
			check("M1", "the importer writes one .translation per language column, next to the CSV, inside the project",
				files.has("strings.en.translation") and files.has("strings.pt.translation"),
				"files = " + str(files))
			check("M2", "it also writes strings.csv.import next to the CSV; the only thing under .godot/ is an .md5",
				files.has("strings.csv.import") and imported_md5_count() == 1,
				".godot/imported/*.md5 count = " + str(imported_md5_count()))
			check("M3", "the setting the engine reads at startup names the .translation files, never the .csv",
				registered.size() == 2 \
				and String(registered[0]).ends_with(".translation") \
				and not str(registered).contains(".csv"),
				"registered = " + str(registered))
			check("M14", "the uid is minted at the first import and lives in strings.csv.import, not in the CSV",
				FileAccess.get_file_as_string("res://strings.csv.import").contains("uid://") \
				and not FileAccess.get_file_as_string("res://strings.csv").contains("uid://"))

		"no_godot_dir":
			check("M5", "with the .translation files committed, a clone with no .godot/ translates with no editor pass at all",
				greeting == "Hello", "tr(\"GREETING\") = " + greeting)

		"no_translation_files":
			check("M6", "with the .translation files missing, the game returns the key",
				greeting == "GREETING" \
				and not FileAccess.file_exists("res://strings.en.translation"),
				"tr(\"GREETING\") = " + greeting)

		"no_import_file":
			check("M7", "strings.csv.import takes no part at run time: delete it and the game still translates",
				greeting == "Hello" and not files.has("strings.csv.import"),
				"files = " + str(files))

		"no_csv":
			check("M8", "the CSV takes no part at run time either: delete it and the game still translates",
				greeting == "Hello" and not files.has("strings.csv"),
				"files = " + str(files))

		"stale_translation":
			var csv := FileAccess.get_file_as_string("res://strings.csv")
			check("M9", "a stale .translation beside an edited CSV ships the OLD text, with no error and no warning",
				greeting == "Hello" and csv.contains("BRAND NEW TEXT"),
				"CSV says BRAND NEW TEXT, tr(\"GREETING\") = " + greeting)

		"after_editor_pass":
			check("M10", "one editor pass regenerates the file and the edited text appears",
				greeting == "BRAND NEW TEXT", "tr(\"GREETING\") = " + greeting)

		"cross_read_ok":
			check("M13", "a newer engine reads a .translation generated by an older one",
				greeting == "Hello", "tr(\"GREETING\") = " + greeting)

		"cross_read_refused":
			check("M12", "an older engine refuses a .translation generated by a newer one and returns the key",
				greeting == "GREETING" \
				and FileAccess.file_exists("res://strings.en.translation"),
				"file is on disk, tr(\"GREETING\") = " + greeting)

		_:
			print("FAIL  ??  unknown case name: " + c)
			failures += 1

	print("CASEEND " + c + " " + str(failures) + " " + str(measured))
	quit(0)
